#!/usr/bin/env bash

aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin 993874376304.dkr.ecr.us-east-1.amazonaws.com/open_gov_puller
podman manifest push --all open_gov_puller:latest 993874376304.dkr.ecr.us-east-1.amazonaws.com/open_gov_puller:latest
